"""update userInfo3

Revision ID: 02313de908a5
Revises: 1a3fbe6ef5c3
Create Date: 2023-09-17 17:04:07.848667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02313de908a5'
down_revision: Union[str, None] = '1a3fbe6ef5c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_user_info_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'user_info_id')
    op.add_column('user_info', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_info', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_info', type_='foreignkey')
    op.drop_column('user_info', 'user_id')
    op.add_column('user', sa.Column('user_info_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_user_info_id_fkey', 'user', 'user_info', ['user_info_id'], ['id'])
    # ### end Alembic commands ###
