"""update userInfo4

Revision ID: 1f2df695fd3e
Revises: 02313de908a5
Create Date: 2023-09-17 17:32:44.203532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f2df695fd3e'
down_revision: Union[str, None] = '02313de908a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_info_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user_info', ['user_info_id'], ['id'])
    op.drop_constraint('user_info_user_id_fkey', 'user_info', type_='foreignkey')
    op.drop_column('user_info', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_info_user_id_fkey', 'user_info', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_info_id')
    # ### end Alembic commands ###
