"""generate user_info_table

Revision ID: d27f7aa7c5fe
Revises: a4f71b3f60ff
Create Date: 2023-09-17 14:55:00.891131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27f7aa7c5fe'
down_revision: Union[str, None] = 'a4f71b3f60ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatar_id'), 'avatar', ['id'], unique=False)
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_info_id'), 'user_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_info_id'), table_name='user_info')
    op.drop_table('user_info')
    op.drop_index(op.f('ix_avatar_id'), table_name='avatar')
    op.drop_table('avatar')
    # ### end Alembic commands ###
